### ISSUE TITLE
Using images for builds

### ISSUE THREAD

**Issue by kiliczsh** [enderahmetyurt/podiscover#101]
I think using this docker-compose.yml will be enough to run on production. This can be documented no need to add some files in my opinion: 

```yaml
version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always

  podiscover:
    image: eaydev/podiscover:e41c7ab311fb7334d6249daf307206293d7c56a1
    environment:
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: production
      RACK_ENV: production
    depends_on:
      - redis

volumes:
  bundle:


```

* `image: eaydev/podiscover:latest` can also be used for latest image.
